### ISSUE TITLE
Bug when including .js file in an import

### ISSUE THREAD

**Issue by manubb** [kapouer/bundledom#6]
Bundling an import which loads a js file produces incorrect js that crashes on the client. Maybe this is related to issue #5. The .js file concerned is tab.js from semantic-ui.

**Comment by kapouer** [comment]
This is because once minified, tab.js contains `$&` which is recognized as a replacement pattern if it occurs inside `replacement` in `str.replace(re, replacement)`. Fixing using a replacement function instead.
